# Generated by Django 4.2.1 on 2023-05-25 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_desk_host_post_desk_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
